"""High-performance cached data services for the Streamlit app."""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from .data_processing import (
    ENRICH_COLUMNS,
    MAIN_REQUIRED_COLUMNS,
    build_platemap_lookups,
    discover_local_platemap_files,
    normalize_id,
    normalize_main_dataframe,
    normalize_platemap_dataframe,
)

logger = logging.getLogger(__name__)


@dataclass
class DataFreshness:
    source_repo: str
    source_branch: str
    source_commit: str
    generated_at: str
    schema_version: str


class DNACollectionDataService:
    """Service object that serves all data operations from cache artifacts."""

    def __init__(self, base_path: str):
        self.base_path = Path(base_path)
        self.cache_dir = self.base_path / "data" / "cache"
        self.manifest: Dict = {}

        self.main_df = pd.DataFrame(columns=MAIN_REQUIRED_COLUMNS + ["ODC_ID_NORM", "BBF_ID_NORM"])
        self.platemaps_df = pd.DataFrame()
        self.odc_lookup = pd.DataFrame(columns=ENRICH_COLUMNS)
        self.bbf_lookup = pd.DataFrame(columns=ENRICH_COLUMNS)

        self.genbank_index_df = pd.DataFrame(
            columns=["part_id", "file_path", "length", "gc_content", "record_id", "description"]
        )

        self._load_cache_artifacts()

    def _load_cache_artifacts(self) -> None:
        """Load manifest-driven cache artifacts.

        The app is designed to read cached artifacts generated by scripts/sync_upstream_data.py.
        """
        manifest_path = self.cache_dir / "manifest.json"
        if manifest_path.exists():
            with manifest_path.open("r", encoding="utf-8") as f:
                self.manifest = json.load(f)

            self.main_df = self._load_parquet("main.parquet")
            self.platemaps_df = self._load_parquet("platemaps.parquet")

            odc_lookup_path = self.cache_dir / "platemap_lookup_odc.parquet"
            bbf_lookup_path = self.cache_dir / "platemap_lookup_bbf.parquet"
            if odc_lookup_path.exists() and bbf_lookup_path.exists():
                self.odc_lookup = pd.read_parquet(odc_lookup_path)
                self.bbf_lookup = pd.read_parquet(bbf_lookup_path)
                if "ODC_ID_NORM" in self.odc_lookup.columns:
                    self.odc_lookup = self.odc_lookup.set_index("ODC_ID_NORM")
                if "BBF_ID_NORM" in self.bbf_lookup.columns:
                    self.bbf_lookup = self.bbf_lookup.set_index("BBF_ID_NORM")
            else:
                self.odc_lookup, self.bbf_lookup = build_platemap_lookups(self.platemaps_df)

            genbank_index_path = self.cache_dir / "genbank_index.parquet"
            if genbank_index_path.exists():
                self.genbank_index_df = pd.read_parquet(genbank_index_path)

            logger.info(
                "Loaded cached artifacts: main=%s, platemaps=%s, genbank_index=%s",
                len(self.main_df),
                len(self.platemaps_df),
                len(self.genbank_index_df),
            )
            return

        # Developer fallback for local runs if cache was not generated yet.
        logger.warning("Cache manifest not found; building local in-memory fallback data")
        self._load_local_fallback_data()

    def _load_parquet(self, filename: str) -> pd.DataFrame:
        path = self.cache_dir / filename
        if not path.exists():
            return pd.DataFrame()
        return pd.read_parquet(path)

    def _load_local_fallback_data(self) -> None:
        main_csv = self.base_path / "odc_plasmids.csv"
        if main_csv.exists():
            self.main_df = normalize_main_dataframe(pd.read_csv(main_csv))

        platemap_frames: List[pd.DataFrame] = []
        for platemap_path in discover_local_platemap_files(self.base_path):
            toolkit = platemap_path.parent.parent.name
            version = platemap_path.stem
            df = pd.read_csv(platemap_path)
            platemap_frames.append(
                normalize_platemap_dataframe(
                    df=df,
                    toolkit=toolkit,
                    version=version,
                    source_path=str(platemap_path.relative_to(self.base_path)),
                )
            )

        if platemap_frames:
            self.platemaps_df = pd.concat(platemap_frames, ignore_index=True)
            self.odc_lookup, self.bbf_lookup = build_platemap_lookups(self.platemaps_df)

    def get_data_freshness(self) -> DataFreshness:
        return DataFreshness(
            source_repo=self.manifest.get("source_repo", "local-fallback"),
            source_branch=self.manifest.get("source_branch", "local"),
            source_commit=self.manifest.get("source_commit", "n/a"),
            generated_at=self.manifest.get("generated_at", "n/a"),
            schema_version=self.manifest.get("schema_version", "n/a"),
        )

    def get_diagnostics(self) -> Dict[str, object]:
        return {
            "main_rows": int(len(self.main_df)),
            "platemap_rows": int(len(self.platemaps_df)),
            "platemap_odc_lookup_keys": int(len(self.odc_lookup)),
            "platemap_bbf_lookup_keys": int(len(self.bbf_lookup)),
            "genbank_index_rows": int(len(self.genbank_index_df)),
            "cache_dir": str(self.cache_dir),
            "has_manifest": bool(self.manifest),
        }

    def get_collections_summary(self) -> Dict:
        summary: Dict[str, Dict] = {}

        if not self.main_df.empty:
            collection_counts = self.main_df["Collection"].fillna("Unknown").value_counts()
            for collection, count in collection_counts.items():
                collection_df = self.main_df[self.main_df["Collection"] == collection]
                summary[collection] = {
                    "count": int(count),
                    "with_bbf_id": int(collection_df["BBF ID"].notna().sum()),
                    "with_odc_id": int(collection_df["ODC ID"].notna().sum()),
                }

        lengths = self.genbank_index_df.get("length", pd.Series([], dtype="float64"))
        summary["GenBank Files"] = {
            "count": int(len(self.genbank_index_df)),
            "total_sequences": int(len(self.genbank_index_df)),
            "avg_length": float(lengths.mean()) if not lengths.empty else 0.0,
        }
        return summary

    def _enrich_with_platemap_info(self, df: pd.DataFrame) -> pd.DataFrame:
        """Vectorized enrichment using precomputed hash lookups."""
        result = df.copy()

        if self.odc_lookup.empty and self.bbf_lookup.empty:
            for col in [
                "Well_Location",
                "Bacterial_Resistance",
                "Growth_Strain",
                "Growth_Conditions",
                "Platemap_Version",
                "Platemap_Key",
            ]:
                if col not in result.columns:
                    result[col] = None
            return result

        # Join using isolated key frames so lookup columns are not shadowed by pre-existing columns.
        odc_join = result[["ODC_ID_NORM"]].join(self.odc_lookup, on="ODC_ID_NORM")
        bbf_join = result[["BBF_ID_NORM"]].join(self.bbf_lookup, on="BBF_ID_NORM")

        for col in ENRICH_COLUMNS:
            odc_series = odc_join[col] if col in odc_join.columns else pd.Series([None] * len(result), index=result.index)
            bbf_series = bbf_join[col] if col in bbf_join.columns else pd.Series([None] * len(result), index=result.index)
            result[col] = odc_series.combine_first(bbf_series)

        # Keep compatibility with existing UI column naming.
        result["Well_Location"] = result["Well_Location"]
        result["Bacterial_Resistance"] = result["Bacterial_Resistance"]
        result["Growth_Strain"] = result["Growth_Strain"]
        result["Growth_Conditions"] = result["Growth_Conditions"]
        result["Platemap_Version"] = result["Platemap_Version"]
        return result

    def _apply_platemap_filters(self, df: pd.DataFrame, filters: Dict) -> pd.DataFrame:
        filtered_df = df.copy()

        if "resistance" in filters:
            filtered_df = filtered_df[
                filtered_df["Bacterial_Resistance"].astype(str).str.contains(filters["resistance"], case=False, na=False)
            ]

        if "strain" in filters:
            filtered_df = filtered_df[
                filtered_df["Growth_Strain"].astype(str).str.contains(filters["strain"], case=False, na=False)
            ]

        if "well_pattern" in filters:
            pattern = filters["well_pattern"].replace("*", ".*")
            filtered_df = filtered_df[
                filtered_df["Well_Location"].astype(str).str.match(pattern, case=False, na=False)
            ]

        return filtered_df

    def search_parts(
        self,
        query: str,
        collection: Optional[str] = None,
        platemap_filters: Optional[Dict] = None,
    ) -> pd.DataFrame:
        if self.main_df.empty:
            return pd.DataFrame()

        df = self.main_df.copy()

        if collection and collection != "All Collections":
            df = df[df["Collection"] == collection]

        if query:
            q = query.strip()
            mask = (
                df["Name"].str.contains(q, case=False, na=False, regex=False)
                | df["BBF ID"].astype(str).str.contains(q, case=False, na=False, regex=False)
                | df["ODC ID"].astype(str).str.contains(q, case=False, na=False, regex=False)
                | df["Collection"].str.contains(q, case=False, na=False, regex=False)
            )
            df = df[mask]

        df = self._enrich_with_platemap_info(df)

        if platemap_filters:
            df = self._apply_platemap_filters(df, platemap_filters)

        return df.reset_index(drop=True)

    def _lookup_basic_info(self, part_id: str) -> Dict:
        part_norm = normalize_id(part_id)
        if not part_norm or self.main_df.empty:
            return {}

        matches = self.main_df[
            (self.main_df["ODC_ID_NORM"] == part_norm)
            | (self.main_df["BBF_ID_NORM"] == part_norm)
        ]
        if matches.empty:
            return {}
        return matches.iloc[0].to_dict()

    def _find_genbank_file(self, part_id: str, basic_info: Dict) -> Optional[Path]:
        if self.genbank_index_df.empty:
            return None

        candidate_ids = [normalize_id(part_id)]
        if basic_info:
            candidate_ids.append(normalize_id(basic_info.get("ODC ID")))
            candidate_ids.append(normalize_id(basic_info.get("BBF ID")))

        candidate_ids = [c for c in candidate_ids if c]

        for candidate in candidate_ids:
            rows = self.genbank_index_df[self.genbank_index_df["part_id"] == candidate]
            if not rows.empty:
                file_path = rows.iloc[0].get("file_path")
                if file_path:
                    resolved = self.base_path / str(file_path)
                    if resolved.exists():
                        return resolved
        return None

    def _parse_genbank_details(self, file_path: Path, part_id: str) -> Dict:
        """Parse a GenBank file lazily when user opens part details."""
        try:
            from Bio import SeqIO  # Imported lazily to keep startup fast.
            try:
                from Bio.SeqUtils import GC
            except ImportError:
                from Bio.SeqUtils import gc_fraction

                def GC(seq):
                    return gc_fraction(seq) * 100

            with file_path.open("r", encoding="utf-8", errors="ignore") as f:
                record = SeqIO.read(f, "genbank")
                return {
                    "record": record,
                    "file_path": str(file_path),
                    "sequence": str(record.seq),
                    "length": len(record.seq),
                    "gc_content": GC(record.seq),
                    "features": len(record.features),
                    "description": record.description,
                    "record_id": record.id,
                }
        except Exception as exc:
            logger.warning("Failed parsing GenBank file %s: %s", file_path, exc)
            return {}

    def get_part_details(self, part_id: str) -> Dict:
        details: Dict[str, Dict] = {}
        basic_info = self._lookup_basic_info(part_id)
        if basic_info:
            details["basic_info"] = basic_info

        genbank_file = self._find_genbank_file(part_id, basic_info)
        if genbank_file:
            gb_details = self._parse_genbank_details(genbank_file, part_id)
            if gb_details:
                details["genbank"] = gb_details

        return details

    def get_platemap_summary(self) -> pd.DataFrame:
        if self.platemaps_df.empty:
            return pd.DataFrame()

        grouped = []
        for key, group_df in self.platemaps_df.groupby("Platemap_Key", dropna=False):
            grouped.append(
                {
                    "Platemap_Key": key,
                    "Toolkit": group_df["Toolkit"].iloc[0],
                    "Version": group_df["Platemap_Version"].iloc[0],
                    "Total Wells": int(len(group_df)),
                    "Filled Wells": int(group_df["Name"].notna().sum()),
                    "Unique Resistances": int(group_df["Bacterial_Resistance"].nunique(dropna=True)),
                    "Unique Strains": int(group_df["Growth_Strain"].nunique(dropna=True)),
                }
            )

        return pd.DataFrame(grouped).sort_values(["Toolkit", "Version"]).reset_index(drop=True)

    def get_platemap(self, platemap_key: str) -> pd.DataFrame:
        if self.platemaps_df.empty:
            return pd.DataFrame()
        return self.platemaps_df[self.platemaps_df["Platemap_Key"] == platemap_key].reset_index(drop=True)

    def get_sequence_stats(self) -> pd.DataFrame:
        if self.genbank_index_df.empty:
            return pd.DataFrame(columns=["length", "gc_content"])
        return self.genbank_index_df[["length", "gc_content"]].dropna()

    def resolve_genbank_file_for_part(self, part_id: str) -> Optional[Path]:
        basic = self._lookup_basic_info(part_id)
        return self._find_genbank_file(part_id, basic)
